services:
  app:
    build:
      context:
        ./app
    ports:
      - "8080:8000"
    networks:
      - net
    depends_on:
      - api
  api:
    build:
      context:
        ./api
    ports:
      - "8090:8000"
    networks:
      - net
    volumes:
      - ../../models:/api/models
networks:
  net:
    driver: bridge